version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dados:/var/lib/postgres/data
      # scripts do banco
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
    - ./web:/usr/share/nginx/html/
    # configuracao do proxy reverso
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    # comando bash usado para evitar problemas de permissao
    command: bash ./app.sh
    networks:
      - banco
      - web
      - fila
    depends_on:
      - db
      - queue
    environment:
      - DB_NAME=email_sender
  queue:
    image: redis:3.2
    networks:
      - fila
  worker: 
    # procurar na pastar worker o Dockerfile
    build: worker
    volumes:
    - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on: 
      - queue
      - app