version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dados:/var/lib/postgres/data
      # scripts do banco
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
    - ./web:/usr/share/nginx/html/
    # configuracao do proxy reverso
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    # comando bash usado para evitar problemas de permissao
    command: bash ./app.sh

